import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import i18nConfig from "@/i18n-config";
import { dir } from "i18next";

import { AppTheme } from "./utils/theme";
import { Suspense } from "react";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Spotify",
  description: "Generated by Tambi",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={`${montserrat.variable} antialiased`}>
        <Suspense fallback="loading">
          <AppTheme>{children}</AppTheme>
        </Suspense>
      </body>
    </html>
  );
}
